# Generated by Django 2.0 on 2019-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pwd',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
