# Generated by Django 2.0 on 2019-07-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20190703_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default='Shah', max_length=50),
        ),
    ]
